### ISSUE TITLE
The vxlan tool sent back SSH traffic received

### ISSUE THREAD

**Issue by mah88** [anfredette/vxlan_tool#1]
If I connected to the VM using SSH and run the tool with "-i eth0","-d forward" and "-v on", I found it Send many packets with no end. That means it send back all SSH TCP packets. 

So how to solve the issue ? I used it on Ubuntu VM.

**Comment by anfredette** [comment]
The official version (including changes made here) can be seen here:
https://github.com/opendaylight/sfc/blame/master/sfc-test/nsh-tools/vxlan_tool.py

Or better yet, see the following for the official SFC project page and repo:
https://wiki.opendaylight.org/view/Service_Function_Chaining:Main

This is a simple tool for emulating an NSH aware service function for test and development purposes.  It wasn't written to be used on the same port as an SSH session, and apparently doesn't work for that use case.  Feel free to propose changes to make it work, but please do so on the official channels shown above.
